<?php
$bean = \RedBeanPHP\R::dispense('aidevjobs');
$bean->job_uid = 'schema-job-uid-placeholder';
$bean->member = $member;
$bean->boards = $board;
$bean->repoconnections = $repo;
$bean->runners_id = null;
$bean->issue_key = 'SCHEMA-1';
$bean->cloud_uid = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx';
$bean->status = 'pending';
$bean->progress = 0;
$bean->current_step = 'Initializing';
$bean->steps_completed = '[]';
$bean->current_shard_job_uid = 'schema_shard_job_uid';
$bean->branch_name = 'feature/schema-branch';
$bean->pr_url = 'https://github.com/example/repo/pull/1';
$bean->pr_number = 0;
$bean->pr_created_at = date('Y-m-d H:i:s');
$bean->clarification_comment_uid = 'schema_comment_uid';
$bean->clarification_questions = '[]';
$bean->error_message = 'Schema placeholder error message';
$bean->run_count = 0;
$bean->last_output = 'Schema placeholder output';
$bean->last_result_json = '{}';
$bean->files_changed = '[]';
$bean->commit_sha = 'abc123def456';
$bean->shopify_themeid = 0;
$bean->shopify_preview_url = 'https://example.myshopify.com';
$bean->playwright_results = '[]';
$bean->preserve_branch = true;
$bean->started_at = date('Y-m-d H:i:s');
$bean->completed_at = date('Y-m-d H:i:s');
$bean->created_at = date('Y-m-d H:i:s');
$bean->updated_at = date('Y-m-d H:i:s');
$bean->project_type = 'jira';
$bean->queue_metadata = '{}';
$bean->workspace_slug = 'schema_workspace';
$bean->work_dir = '/tmp/schema-work-dir';
$bean->job_token = 'schema_job_token_placeholder';
$bean->token_expires_at = date('Y-m-d H:i:s', strtotime('+24 hours'));
$bean->phase = 'setup';
$bean->summary = 'Schema placeholder summary';
$bean->prompt = 'Schema placeholder prompt';
$bean->claude_md = 'Schema placeholder claude.md content';
$bean->mcp_config_json = '{"mcpServers":{}}';
$bean->env_script = '#!/bin/bash\n# Schema placeholder env script';
$bean->aiagents_id = null;
$bean->delay = 0;
\RedBeanPHP\R::store($bean);
\RedBeanPHP\R::trash($bean);

\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` MODIFY COLUMN `steps_completed` JSON');
\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` MODIFY COLUMN `clarification_questions` JSON');
\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` MODIFY COLUMN `files_changed` JSON');
\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` MODIFY COLUMN `playwright_results` JSON');
\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` MODIFY COLUMN `mcp_config_json` JSON');
\RedBeanPHP\R::exec('ALTER TABLE `aidevjobs` ADD UNIQUE INDEX IF NOT EXISTS `uk_job_uid` (`job_uid`)');
