<?php
$bean = \RedBeanPHP\R::dispense('ctostories');
$bean->ceodirectives = $directive;
$bean->ctoepics = $epic ?? null;
$bean->member = $member;
$bean->boards = $board;
$bean->repoconnections = $repo;
$bean->story_uid = bin2hex(random_bytes(16));
$bean->title = 'Schema Story Title';
$bean->name = 'Schema Story';
$bean->description = 'Schema story description';
$bean->status = 'pending';
$bean->priority = 'normal';
$bean->sequence = 1;
$bean->story_points = 3;
$bean->acceptance_criteria = '["Schema acceptance criteria"]';
$bean->implementation_notes = 'Schema implementation notes';
$bean->depends_on = '[]';
$bean->jira_issue_key = 'SCHEMA-1';
$bean->jira_issue_id = '12345';
$bean->jira_issue_url = 'https://example.atlassian.net/browse/SCHEMA-1';
$bean->aidev_job_uid = 'schema-job-uid';
$bean->blocker_reason = 'Schema placeholder blocker reason';
$bean->verification_result = '{"status": "schema"}';
$bean->started_at = date('Y-m-d H:i:s');
$bean->completed_at = date('Y-m-d H:i:s');
$bean->verified_at = date('Y-m-d H:i:s');
$bean->created_at = date('Y-m-d H:i:s');
$bean->updated_at = date('Y-m-d H:i:s');
\RedBeanPHP\R::store($bean);
\RedBeanPHP\R::trash($bean);
