/**
 * MyCTOBot Client SDK - {{APP_NAME}}
 *
 * Provides client-side pipeline integration for detachable apps.
 * Auto-intercepts forms with data-pipeline attributes and loads
 * pipeline data into elements with data-pipeline-load attributes.
 *
 * Generated by MyCTOBot Detachable App Builder
 * Version: {{APP_VERSION}}
 */
(function() {
    'use strict';

    var MyCTOBot = {
        baseUrl: window.location.origin,

        /**
         * Call a pipeline via the local API proxy.
         *
         * @param {string} slug    Pipeline slug to execute
         * @param {object} input   Input data for the pipeline
         * @returns {Promise<object>} Pipeline result
         */
        callPipeline: async function(slug, input) {
            input = input || {};

            var response = await fetch(this.baseUrl + '/api/pipeline/' + encodeURIComponent(slug), {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(input)
            });

            var data = await response.json();

            document.dispatchEvent(new CustomEvent('pipeline-result', {
                detail: { slug: slug, success: data.success, data: data }
            }));

            return data;
        },

        /**
         * Initialize auto-bindings for forms and data-loading elements.
         */
        init: function() {
            var self = this;

            // Save original button text for all pipeline forms
            document.querySelectorAll('form[data-pipeline] [type="submit"]').forEach(function(btn) {
                btn.setAttribute('data-original-text', btn.textContent);
            });

            // Auto-intercept forms with data-pipeline attribute
            document.addEventListener('submit', async function(e) {
                var form = e.target;
                var slug = form.getAttribute('data-pipeline');
                if (!slug) return;

                e.preventDefault();

                var formData = new FormData(form);
                var input = Object.fromEntries(formData.entries());
                var btn = form.querySelector('[type="submit"]');

                if (btn) {
                    btn.disabled = true;
                    btn.textContent = 'Processing...';
                }

                try {
                    await self.callPipeline(slug, input);
                } finally {
                    if (btn) {
                        btn.disabled = false;
                        btn.textContent = btn.getAttribute('data-original-text') || 'Submit';
                    }
                }
            });

            // Auto-load elements with data-pipeline-load attribute
            document.querySelectorAll('[data-pipeline-load]').forEach(async function(el) {
                var slug = el.getAttribute('data-pipeline-load');
                var inputAttr = el.getAttribute('data-pipeline-input');
                var input = inputAttr ? JSON.parse(inputAttr) : {};

                el.innerHTML = '<div class="text-center p-3"><div class="spinner-border spinner-border-sm"></div> Loading...</div>';

                try {
                    var result = await self.callPipeline(slug, input);
                    if (result.html) {
                        el.innerHTML = result.html;
                    } else if (result.output) {
                        el.innerHTML = '<pre>' + JSON.stringify(result.output, null, 2) + '</pre>';
                    } else {
                        el.innerHTML = '<pre>' + JSON.stringify(result, null, 2) + '</pre>';
                    }
                } catch (err) {
                    el.innerHTML = '<div class="alert alert-danger">Failed to load data</div>';
                }
            });
        }
    };

    window.MyCTOBot = MyCTOBot;

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() { MyCTOBot.init(); });
    } else {
        MyCTOBot.init();
    }
})();
