<?php
/**
 * {{APP_NAME}} - Configuration
 *
 * Reads from environment variables with template defaults.
 * Override values via .env file or Docker environment.
 *
 * Generated by MyCTOBot Detachable App Builder
 * Workspace: {{WORKSPACE}}
 */

return [
    'myctobot_api_url' => getenv('MYCTOBOT_API_URL') ?: '{{DEFAULT_API_URL}}',
    'api_token' => getenv('MYCTOBOT_API_TOKEN') ?: '',
    'workspace' => getenv('MYCTOBOT_WORKSPACE') ?: '{{WORKSPACE}}',
    'app_name' => '{{APP_NAME}}',
    'app_slug' => '{{APP_SLUG}}',
    'allowed_pipelines' => json_decode('{{ALLOWED_PIPELINES_JSON}}', true) ?: [],
];
