<?php
/**
 * {{APP_NAME}} - API Router
 *
 * Lightweight PHP router for the detachable app.
 * Handles health checks and proxies pipeline calls to MyCTOBot.
 *
 * Generated by MyCTOBot Detachable App Builder
 * Workspace: {{WORKSPACE}}
 */

header('Content-Type: application/json');

$config = require __DIR__ . '/config.php';
require __DIR__ . '/proxy.php';

$requestUri = $_SERVER['REQUEST_URI'] ?? '/';
$requestMethod = $_SERVER['REQUEST_METHOD'] ?? 'GET';

// Strip query string for routing
$path = parse_url($requestUri, PHP_URL_PATH);

// Route: GET /health
if ($path === '/health' && $requestMethod === 'GET') {
    echo json_encode([
        'status' => 'ok',
        'app' => $config['app_name'],
        'slug' => $config['app_slug'],
        'timestamp' => date('c'),
    ]);
    exit;
}

// Route: POST /api/pipeline/{slug}
if (preg_match('#^/api/pipeline/([a-z0-9_-]+)$#', $path, $matches) && $requestMethod === 'POST') {
    $pipelineSlug = $matches[1];

    $rawBody = file_get_contents('php://input');
    $input = json_decode($rawBody, true);

    if ($rawBody !== '' && $input === null) {
        http_response_code(400);
        echo json_encode([
            'success' => false,
            'error' => 'Invalid JSON in request body',
        ]);
        exit;
    }

    $result = proxyPipelineCall($pipelineSlug, $input ?: [], $config);

    if (!$result['success']) {
        http_response_code($result['http_status'] ?? 500);
    }

    echo json_encode($result);
    exit;
}

// Fallback: 404
http_response_code(404);
echo json_encode([
    'success' => false,
    'error' => 'Not found',
    'path' => $path,
]);
