<?php
/**
 * {{APP_NAME}} - Pipeline Proxy
 *
 * Proxies pipeline calls to the MyCTOBot API with authentication.
 * Validates pipeline slugs against an allowlist before forwarding.
 *
 * Generated by MyCTOBot Detachable App Builder
 * Workspace: {{WORKSPACE}}
 */

/**
 * Proxy a pipeline call to the MyCTOBot API.
 *
 * @param string $slug    Pipeline slug to execute
 * @param array  $input   Input data for the pipeline
 * @param array  $config  App configuration from config.php
 * @return array Response with 'success' key and either data or 'error'
 */
function proxyPipelineCall(string $slug, array $input, array $config): array
{
    // Validate pipeline slug against allowlist
    if (!empty($config['allowed_pipelines']) && !in_array($slug, $config['allowed_pipelines'], true)) {
        return [
            'success' => false,
            'error' => 'Pipeline not allowed: ' . $slug,
            'http_status' => 403,
        ];
    }

    // Validate API token is configured
    if (empty($config['api_token'])) {
        return [
            'success' => false,
            'error' => 'API token not configured. Set MYCTOBOT_API_TOKEN in .env',
            'http_status' => 500,
        ];
    }

    $url = rtrim($config['myctobot_api_url'], '/') . '/api/pipelines/' . urlencode($slug) . '/run?sync=true';
    $payload = json_encode(['input' => $input]);

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => $url,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $payload,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 120,
        CURLOPT_CONNECTTIMEOUT => 10,
        CURLOPT_HTTPHEADER => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $config['api_token'],
            'X-Workspace: ' . $config['workspace'],
            'Accept: application/json',
        ],
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    $curlErrno = curl_errno($ch);
    curl_close($ch);

    // Handle curl-level failures
    if ($curlErrno !== 0) {
        return [
            'success' => false,
            'error' => 'Failed to connect to MyCTOBot API: ' . $curlError,
            'http_status' => 502,
        ];
    }

    // Parse response
    $data = json_decode($response, true);

    if ($data === null && $response !== '') {
        return [
            'success' => false,
            'error' => 'Invalid response from MyCTOBot API',
            'http_status' => 502,
            'raw_status' => $httpCode,
        ];
    }

    // Forward HTTP error status
    if ($httpCode >= 400) {
        return [
            'success' => false,
            'error' => $data['error'] ?? $data['message'] ?? 'API returned HTTP ' . $httpCode,
            'http_status' => $httpCode,
            'details' => $data,
        ];
    }

    // Return successful response
    return array_merge(['success' => true, 'http_status' => $httpCode], $data ?: []);
}
