<?php
/**
 * Pipeline Engine Configuration
 *
 * Persistent OpenSwoole service for pipeline execution.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by PipelineEngineBuilder
 */

return [
    // Server settings
    'host' => '0.0.0.0',
    'port' => {{PORT}},
    'workers' => {{WORKERS}},

    // Engine metadata
    'service_id' => {{SERVICE_ID}},
    'workspace' => '{{WORKSPACE}}',

    // Auth token for internal requests
    'engine_token' => '{{ENGINE_TOKEN}}',

    // Debug mode
    'debug' => {{DEBUG}},
];
