<?php
declare(strict_types=1);
/**
 * Pipeline Engine Server
 *
 * Persistent OpenSwoole HTTP server for pipeline execution.
 * Pre-loads vendor, DB connection, and logger — eliminates per-request bootstrap cost.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by PipelineEngineBuilder
 */

// Use main MyCTOBot vendor (no duplication)
require_once '{{MYCTOBOT_ROOT}}/vendor/autoload.php';
require_once __DIR__ . '/bootstrap.php';

use OpenSwoole\Http\Server;
use OpenSwoole\Http\Request;
use OpenSwoole\Http\Response;
use app\services\TenantAppDatabase;
use app\services\PipelineExecutor;
use app\Bean;

$config = require __DIR__ . '/config.php';

// Initialize logger
$logger = new \app\services\TenantAppLogger('{{WORKSPACE}}', 'pipeline-engine', true);
$logger->info('Starting pipeline engine on port {port}', ['port' => $config['port']]);

// Initialize database for this workspace
TenantAppDatabase::init('{{WORKSPACE}}');

$server = new Server($config['host'], $config['port']);
$server->set([
    'worker_num' => $config['workers'],
    'log_file' => __DIR__ . '/storage/logs/swoole.log',
    'pid_file' => __DIR__ . '/storage/engine.pid',
    'daemonize' => false,  // Managed by tmux
    'max_request' => 5000, // Worker rotation to prevent memory leaks
    'dispatch_mode' => 2,
]);

$startTime = time();

$server->on('start', function($server) use ($config, $logger, $startTime) {
    file_put_contents(__DIR__ . '/storage/engine.pid', $server->master_pid);
    $logger->info('Pipeline engine started', [
        'host' => $config['host'],
        'port' => $config['port'],
        'workers' => $config['workers'],
        'pid' => $server->master_pid,
    ]);
    echo "[pipeline-engine] Server started on http://{$config['host']}:{$config['port']}\n";
});

$server->on('workerStart', function($server, $workerId) use ($logger) {
    // Re-initialize database connection for this worker
    TenantAppDatabase::init('{{WORKSPACE}}');
    $logger->debug('Worker started', ['worker_id' => $workerId]);
});

$server->on('request', function(Request $request, Response $response) use ($config, $logger, $startTime) {
    $requestStart = microtime(true);

    // Default headers
    $response->header('Content-Type', 'application/json');
    $response->header('X-Engine', 'pipeline-engine');

    $path = $request->server['request_uri'] ?? '/';
    $method = $request->server['request_method'] ?? 'GET';
    $ip = $request->server['remote_addr'] ?? 'unknown';

    // Health check (always public)
    if ($path === '/health' && $method === 'GET') {
        $response->end(json_encode([
            'status' => 'ok',
            'service' => 'pipeline-engine',
            'workspace' => '{{WORKSPACE}}',
            'uptime' => time() - $startTime,
            'workers' => $config['workers'],
        ]));
        return;
    }

    // Auth: internal only (localhost or valid engine token)
    if ($ip !== '127.0.0.1' && $ip !== '::1') {
        $token = $request->header['x-engine-token'] ?? '';
        if ($token !== $config['engine_token']) {
            $response->status(403);
            $response->end(json_encode(['error' => 'Access denied']));
            return;
        }
    }

    try {
        // POST /run — execute a pipeline run
        if ($path === '/run' && $method === 'POST') {
            $body = parseJsonBody($request);
            if (!$body || empty($body['run_id'])) {
                $response->status(400);
                $response->end(json_encode(['error' => 'run_id required']));
                return;
            }

            $runId = (int) $body['run_id'];
            $sync = !empty($body['sync']);

            $logger->info('Executing pipeline run', [
                'run_id' => $runId,
                'sync' => $sync,
            ]);

            $executor = new PipelineExecutor($runId, $logger, '{{WORKSPACE}}');

            if ($sync) {
                // Synchronous: execute and return results
                $executor->execute();

                $run = Bean::load('pipelineruns', $runId);
                $output = json_decode($run->output_json ?: '{}', true);

                $duration = round((microtime(true) - $requestStart) * 1000, 2);
                $response->end(json_encode([
                    'success' => true,
                    'run_id' => $runId,
                    'status' => $run->status,
                    'output' => $output,
                    'completed_at' => $run->completed_at,
                    'duration_ms' => $duration,
                ]));
            } else {
                // Async: execute in a coroutine, return immediately
                // Note: OpenSwoole coroutines allow non-blocking execution within workers
                $response->end(json_encode([
                    'success' => true,
                    'run_id' => $runId,
                    'status' => 'dispatched',
                ]));

                // Execute after responding (still in this worker, but response is sent)
                try {
                    $executor->execute();
                } catch (\Throwable $e) {
                    $logger->error('Async pipeline execution failed', [
                        'run_id' => $runId,
                        'error' => $e->getMessage(),
                    ]);
                    // Update run status to failed
                    $run = Bean::load('pipelineruns', $runId);
                    if ($run && $run->id && $run->status !== 'completed') {
                        $run->status = 'failed';
                        $run->error_message = $e->getMessage();
                        $run->completed_at = date('Y-m-d H:i:s');
                        Bean::store($run);
                    }
                }
            }

            // Cleanup: unset executor to trigger destructor (SSH key cleanup)
            unset($executor);
            return;
        }

        // POST /resume — resume a paused pipeline (await_input)
        if ($path === '/resume' && $method === 'POST') {
            $body = parseJsonBody($request);
            if (!$body || empty($body['run_id']) || empty($body['input_token'])) {
                $response->status(400);
                $response->end(json_encode(['error' => 'run_id and input_token required']));
                return;
            }

            $runId = (int) $body['run_id'];
            $input = $body['input'] ?? [];
            $inputToken = $body['input_token'];
            $source = $body['source'] ?? 'api';

            $logger->info('Resuming pipeline run', [
                'run_id' => $runId,
                'source' => $source,
            ]);

            $executor = new PipelineExecutor($runId, $logger, '{{WORKSPACE}}');
            $result = $executor->resumeFromAwaitInput($input, $inputToken, $source);

            unset($executor);

            $response->end(json_encode($result));
            return;
        }

        // GET /status — engine status and run counts
        if ($path === '/status' && $method === 'GET') {
            $activeRuns = Bean::count('pipelineruns', ' status = ? ', ['running']);
            $pendingRuns = Bean::count('pipelineruns', ' status = ? ', ['pending']);
            $awaitingRuns = Bean::count('pipelineruns', ' status = ? ', ['awaiting_input']);

            $response->end(json_encode([
                'status' => 'ok',
                'workspace' => '{{WORKSPACE}}',
                'uptime' => time() - $startTime,
                'runs' => [
                    'active' => $activeRuns,
                    'pending' => $pendingRuns,
                    'awaiting_input' => $awaitingRuns,
                ],
            ]));
            return;
        }

        // 404
        $response->status(404);
        $response->end(json_encode(['error' => 'Not found', 'path' => $path]));

    } catch (\Throwable $e) {
        $logger->error('Engine request error: {message}', [
            'message' => $e->getMessage(),
            'path' => $path,
            'trace' => $e->getTraceAsString(),
        ]);

        $response->status(500);
        $response->end(json_encode([
            'error' => 'Internal server error',
            'message' => $config['debug'] ? $e->getMessage() : 'An error occurred',
        ]));
    }

    $duration = round((microtime(true) - $requestStart) * 1000, 2);
    $logger->debug('Request completed', [
        'method' => $method,
        'path' => $path,
        'duration_ms' => $duration,
    ]);
});

$server->on('shutdown', function($server) use ($logger) {
    $logger->info('Pipeline engine shutting down');
    @unlink(__DIR__ . '/storage/engine.pid');
});

$server->start();
