# {{APP_NAME}}

**Version:** {{APP_VERSION}}
**Generated:** {{GENERATED_AT}}
**Platform:** MyCTOBot Detachable Apps

---

## Overview

This is a Shopify App Store app bundle for **{{APP_NAME}}**.

**App Handle:** `{{APP_SLUG}}`
**Workspace:** `{{WORKSPACE}}`
**OAuth Scopes:** `{{OAUTH_SCOPES}}`

---

## Contents

### Theme App Extensions

- **Blocks:** {{BLOCKS_COUNT}} files (Shopify 2.0 drag-and-drop components)
- **Embeds:** {{EMBEDS_COUNT}} files (Global scripts)
- **Sections:** {{SECTIONS_COUNT}} files (Full-page layouts)
- **Snippets:** {{SNIPPETS_COUNT}} files (Reusable components)
- **JavaScript Assets:** {{JS_ASSETS_COUNT}} files
- **CSS Assets:** {{CSS_ASSETS_COUNT}} files

### App Proxy

**Proxy URL:** `{{PROXY_URL}}`
**Subpath:** `/apps/myctobot{{PROXY_SUBPATH}}`

The app proxy routes requests to MyCTOBot pipelines for dynamic data fetching.

---

## Installation

### Prerequisites

1. **Shopify CLI** installed: `npm install -g @shopify/cli`
2. **Shopify Partner Account** at https://partners.shopify.com
3. **App registered** in Partner Dashboard with API credentials

### Deploy to Development Store

```bash
cd {{APP_SLUG}}
shopify app dev
```

This will:
- Start local development server
- Install app on your dev store
- Enable hot reloading for theme extensions

### Deploy to Production

```bash
shopify app deploy
```

Then submit for App Store review in Partner Dashboard.

---

## Configuration

### App Credentials

Update `shopify.app.toml` with your app's API credentials:

```toml
client_id = "YOUR_API_KEY_HERE"
```

### App Proxy Setup

In Partner Dashboard, configure App Proxy:
- **Subpath:** `{{PROXY_SUBPATH}}`
- **Proxy URL:** `{{PROXY_URL}}`

---

## Theme Extensions

### Blocks

Merchants can drag these into any section via the theme editor:

{{BLOCK_LIST}}

### Embeds

Global scripts that run on every page (must be enabled in theme settings):

{{EMBED_LIST}}

---

## Pipelines

This app includes embedded pipelines for dynamic functionality:

{{PIPELINE_LIST}}

These pipelines are automatically installed when merchants install your app.

---

## Support

- **Documentation:** https://{{WORKSPACE}}.myctobot.ai/docs
- **API:** https://{{WORKSPACE}}.myctobot.ai/api
- **Support:** support@myctobot.ai

---

## License

Generated by [MyCTOBot](https://myctobot.ai) - AI-Powered App Platform
