# Shopify App Configuration
# Generated by MyCTOBot - {{GENERATED_AT}}
# App: {{APP_NAME}} ({{APP_SLUG}})

name = "{{APP_NAME}}"
client_id = "{{SHOPIFY_API_KEY}}"
application_url = "{{APP_URL}}"
embedded = true

[access_scopes]
scopes = "{{OAUTH_SCOPES}}"

[auth]
redirect_urls = [
  "{{REDIRECT_URL}}"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "{{PROXY_URL}}"
subpath = "{{PROXY_SUBPATH}}"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "{{DEV_STORE_URL}}"
