<?php
/**
 * ShopifyAppBuilder
 *
 * Builds proper Shopify apps from Detachable App configurations
 * using shopify-app-template-react-router and Shopify CLI.
 *
 * Architecture:
 * - Detachable App (screens, pipelines, liquid) → Shopify App
 * - MyCTOBot pipelines = Backend API
 * - Shopify CLI handles deployment
 */

namespace app\services;

use \Exception;
use \app\Bean;

class ShopifyAppBuilder {

    private const TEMPLATE_REPO = 'https://github.com/Shopify/shopify-app-template-react-router.git';

    private string $workspace;
    private string $buildDir;

    public function __construct(string $workspace = 'default') {
        $this->workspace = $workspace;
        $this->buildDir = "/tmp/{$workspace}/shopify-apps";
    }

    /**
     * Build a Shopify app from a Detachable App
     *
     * @param int $detachableAppId Detachable app ID
     * @return array Build result with app path, config, etc.
     */
    public function build(int $detachableAppId): array {
        $app = Bean::load('detachableapps', $detachableAppId);
        if (!$app->id) {
            throw new Exception("Detachable app #{$detachableAppId} not found");
        }

        $appName = $this->sanitizeAppName($app->name ?? 'MyCTOBot App');
        $appSlug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $appName));
        $appDir = $this->buildDir . '/' . $appSlug;

        // 1. Clone template
        $this->cloneTemplate($appDir);

        // 2. Generate shopify.app.toml with scopes
        $scopes = $this->collectScopes($app);
        $this->generateAppConfig($appDir, $appName, $scopes);

        // 3. Generate React routes from screens
        $this->generateScreenRoutes($appDir, $app);

        // 4. Generate pipeline API proxies
        $this->generatePipelineProxies($appDir, $app);

        // 5. Generate Liquid extensions from files
        $this->generateLiquidExtensions($appDir, $app);

        // 6. Generate package.json with backend URL
        $this->updatePackageConfig($appDir, $app);

        return [
            'success' => true,
            'app_dir' => $appDir,
            'app_name' => $appName,
            'app_slug' => $appSlug,
            'next_steps' => [
                "cd {$appDir}",
                "npm install",
                "shopify app deploy"
            ]
        ];
    }

    /**
     * Clone Shopify app template
     */
    private function cloneTemplate(string $appDir): void {
        if (file_exists($appDir)) {
            // Clean existing
            exec("rm -rf " . escapeshellarg($appDir));
        }

        @mkdir($this->buildDir, 0755, true);

        $cmd = sprintf(
            'git clone --depth 1 %s %s 2>&1',
            escapeshellarg(self::TEMPLATE_REPO),
            escapeshellarg($appDir)
        );

        exec($cmd, $output, $exitCode);

        if ($exitCode !== 0) {
            throw new Exception("Failed to clone template: " . implode("\n", $output));
        }

        // Remove .git directory
        exec("rm -rf " . escapeshellarg($appDir . '/.git'));
    }

    /**
     * Collect required Shopify scopes from app config
     */
    private function collectScopes(object $app): array {
        // Default scopes needed for theme apps
        $scopes = [
            'read_themes',
            'write_themes',
            'read_products',
            'read_content'
        ];

        // Add scopes from pipelines
        $pipelines = Bean::find('detachableapppipelines', 'detachableapps_id = ?', [$app->id]);
        foreach ($pipelines as $pipeline) {
            $pipelineBean = Bean::load('pipelines', (int)$pipeline->pipelines_id);
            if ($pipelineBean->id) {
                $steps = Bean::find('pipelinesteps', 'pipelines_id = ?', [$pipelineBean->id]);
                foreach ($steps as $step) {
                    $stepScopes = $this->getScopesForStepType($step->step_type);
                    $scopes = array_merge($scopes, $stepScopes);
                }
            }
        }

        return array_unique($scopes);
    }

    /**
     * Get required scopes for a pipeline step type
     */
    private function getScopesForStepType(string $stepType): array {
        $scopeMap = [
            'shopify_graphql' => ['read_products', 'read_orders', 'read_customers'],
            'email_out' => [],
            'webhook_out' => [],
            // Add more as needed
        ];

        return $scopeMap[$stepType] ?? [];
    }

    /**
     * Generate shopify.app.toml configuration
     */
    private function generateAppConfig(string $appDir, string $appName, array $scopes): void {
        // TOML format: scopes = "scope1, scope2, scope3"
        $scopesStr = implode(', ', $scopes);

        $config = <<<TOML
# Generated by MyCTOBot ShopifyAppBuilder
# NOTE: These are REQUESTED scopes. Actual approved scopes depend on store owner approval.
name = "{$appName}"
scopes = "{$scopesStr}"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

TOML;

        file_put_contents($appDir . '/shopify.app.toml', $config);
    }

    /**
     * Generate React routes from Detachable App screens
     */
    private function generateScreenRoutes(string $appDir, object $app): void {
        $screens = Bean::find('detachableappscreens', 'detachableapps_id = ?', [$app->id]);

        $routes = [];
        foreach ($screens as $screen) {
            $routePath = $this->sanitizeRoutePath($screen->route_path ?? '/');
            $componentName = $this->sanitizeComponentName($screen->screen_name ?? 'Screen');

            // Generate React component
            $this->generateScreenComponent($appDir, $componentName, $screen);

            $routes[] = [
                'path' => $routePath,
                'component' => $componentName
            ];
        }

        // Generate app routing file
        $this->generateAppRoutes($appDir, $routes);
    }

    /**
     * Generate React component for a screen
     */
    private function generateScreenComponent(string $appDir, string $componentName, object $screen): void {
        $content = $screen->content_json ?? '{}';
        $config = json_decode($content, true) ?: [];

        $component = <<<JSX
import { Page, Layout, Card } from "@shopify/polaris";
import { useLoaderData } from "react-router-dom";

export default function {$componentName}() {
  const data = useLoaderData();

  return (
    <Page title="{$screen->screen_name}">
      <Layout>
        <Layout.Section>
          <Card>
            <p>Screen content goes here</p>
            {/* TODO: Render from config: {$content} */}
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
  );
}

export async function loader() {
  // Call MyCTOBot pipeline API
  const response = await fetch(process.env.MYCTOBOT_API_URL + '/api/pipeline/run');
  return await response.json();
}

JSX;

        $routesDir = $appDir . '/app/routes';
        if (!file_exists($routesDir)) {
            mkdir($routesDir, 0755, true);
        }

        file_put_contents("{$routesDir}/{$componentName}.tsx", $component);
    }

    /**
     * Generate app routing configuration
     */
    private function generateAppRoutes(string $appDir, array $routes): void {
        // This would update app/routes/_index.tsx or similar
        // For now, components are auto-discovered by the template
    }

    /**
     * Generate pipeline API proxy routes
     */
    private function generatePipelineProxies(string $appDir, object $app): void {
        $pipelines = Bean::find('detachableapppipelines', 'detachableapps_id = ?', [$app->id]);

        foreach ($pipelines as $appPipeline) {
            $pipeline = Bean::load('pipelines', (int)$appPipeline->pipelines_id);
            if (!$pipeline->id) continue;

            $this->generatePipelineProxy($appDir, $pipeline);
        }
    }

    /**
     * Generate API route that proxies to MyCTOBot pipeline
     */
    private function generatePipelineProxy(string $appDir, object $pipeline): void {
        $pipelineSlug = $pipeline->slug ?? 'pipeline';

        $route = <<<JSX
import { json } from "@remix-run/node";

export async function action({ request }) {
  const formData = await request.formData();
  const payload = Object.fromEntries(formData);

  // Proxy to MyCTOBot pipeline
  const response = await fetch(
    process.env.MYCTOBOT_API_URL + '/pipelines/run/{$pipelineSlug}',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    }
  );

  return json(await response.json());
}

JSX;

        $routesDir = $appDir . '/app/routes/api';
        if (!file_exists($routesDir)) {
            mkdir($routesDir, 0755, true);
        }

        file_put_contents("{$routesDir}/pipeline.{$pipelineSlug}.tsx", $route);
    }

    /**
     * Generate Shopify theme extensions from Liquid files
     * NOTE: Shopify only allows ONE theme extension per app, so we create a single
     * extension with multiple blocks inside it.
     */
    private function generateLiquidExtensions(string $appDir, object $app): void {
        $liquidFiles = Bean::find('detachableappliquidfiles', 'detachableapps_id = ?', [$app->id]);

        // Filter out non-block files
        $blocks = [];
        foreach ($liquidFiles as $file) {
            $fileType = $file->file_type ?? 'app_block';
            // Skip asset files (JS/CSS)
            if (in_array($fileType, ['asset_js', 'asset_css', 'asset'])) {
                continue;
            }
            $blocks[] = $file;
        }

        if (empty($blocks)) {
            return;
        }

        // Create ONE theme extension with all blocks
        $appSlug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $app->name ?? 'app'));
        $extName = $appSlug . '-theme-blocks';
        $extDir = $appDir . '/extensions/' . $extName;

        @mkdir($extDir, 0755, true);

        // Create blocks directory
        $blocksDir = $extDir . '/blocks';
        @mkdir($blocksDir, 0755, true);

        // Create locales directory (required by Shopify CLI)
        $localesDir = $extDir . '/locales';
        @mkdir($localesDir, 0755, true);

        // Create default locale file
        $defaultLocale = [
            'name' => $app->name ?? 'MyCTOBot App',
            'description' => 'Theme blocks created by MyCTOBot'
        ];
        file_put_contents("{$localesDir}/en.default.json", json_encode($defaultLocale, JSON_PRETTY_PRINT));

        // Copy all Liquid blocks into the single extension
        foreach ($blocks as $file) {
            $fileName = $file->file_name ?? 'block.liquid';
            $content = $file->file_content ?? '';

            // Theme app extensions don't support {% script %} tag - convert to HTML <script>
            $content = str_replace(['{% script %}', '{% endscript %}'], ['<script>', '</script>'], $content);

            // Remove empty default values from schema (Shopify validation rejects "default": "")
            $content = preg_replace('/,?\s*"default"\s*:\s*""\s*,?/', '', $content);

            file_put_contents("{$blocksDir}/{$fileName}", $content);
        }

        // Generate extension config (no settings at extension level, blocks have their own)
        $config = [
            'type' => 'theme',
            'name' => $app->name ?? 'MyCTOBot App'
        ];

        file_put_contents("{$extDir}/shopify.extension.toml", $this->tomlEncode($config));
    }

    /**
     * Update package.json with MyCTOBot backend URL
     */
    private function updatePackageConfig(string $appDir, object $app): void {
        $packagePath = $appDir . '/package.json';
        $package = json_decode(file_get_contents($packagePath), true);

        // Add environment variable for backend URL
        $package['config'] = $package['config'] ?? [];
        $package['config']['MYCTOBOT_API_URL'] = 'https://dev.myctobot.ai';

        file_put_contents($packagePath, json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    // Helper methods

    private function sanitizeAppName(string $name): string {
        return preg_replace('/[^a-zA-Z0-9\s-]/', '', $name);
    }

    private function sanitizeRoutePath(string $path): string {
        return '/' . trim($path, '/');
    }

    private function sanitizeComponentName(string $name): string {
        $name = preg_replace('/[^a-zA-Z0-9]/', '', ucwords($name));
        return ucfirst($name);
    }

    private function tomlEncode(array $data): string {
        // Simple TOML encoder for extension config
        $toml = '';
        foreach ($data as $key => $value) {
            if (is_string($value)) {
                $toml .= "{$key} = \"{$value}\"\n";
            } elseif (is_array($value)) {
                // Empty arrays should become empty objects in JSON to avoid TOML validation errors
                if (empty($value)) {
                    $toml .= "{$key} = {}\n";
                } else {
                    $toml .= "{$key} = " . json_encode($value) . "\n";
                }
            }
        }
        return $toml;
    }
}
