<?php
/**
 * WASM Tenant App Bootstrap - {{APP_NAME}}
 *
 * CGI-compatible helper functions (no OpenSwoole dependencies).
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 *
 * NOTE: php-cgi-wasm does not support exit/die. All control flow
 * uses the global $_handled flag to prevent duplicate output.
 */

/**
 * Parse JSON body from php://input
 */
function parseJsonBody(): ?array
{
    $body = file_get_contents('php://input');
    if (empty($body)) {
        return null;
    }
    $data = json_decode($body, true);
    return json_last_error() === JSON_ERROR_NONE ? $data : null;
}

/**
 * Get Bearer token from Authorization header
 */
function getBearerToken(): ?string
{
    $auth = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
    if (preg_match('/^Bearer\s+(.+)$/i', $auth, $matches)) {
        return $matches[1];
    }
    return null;
}

/**
 * Get API key from header or query string
 */
function getApiKey(): ?string
{
    // Check header first
    if (!empty($_SERVER['HTTP_X_API_KEY'])) {
        return $_SERVER['HTTP_X_API_KEY'];
    }
    // Check query string
    return $_GET['api_key'] ?? null;
}

/**
 * Send a JSON response (sets $_handled flag instead of exit)
 */
function jsonResponse(array $data, int $status = 200): void
{
    global $_handled;
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($data);
    $_handled = true;
}

/**
 * Render a view inside the layout
 */
function renderView(string $viewName): string
{
    $viewFile = __DIR__ . '/views/' . $viewName . '.php';
    $layoutFile = __DIR__ . '/views/layout.php';

    if (file_exists($viewFile)) {
        $pageContent = file_get_contents($viewFile);
    } else {
        $pageContent = '<div class="alert alert-warning">View not found: ' . htmlspecialchars($viewName) . '</div>';
    }

    if (file_exists($layoutFile)) {
        ob_start();
        include $layoutFile;
        return ob_get_clean();
    }

    return $pageContent;
}
