<?php
/**
 * WASM Tenant App Router - {{APP_NAME}}
 *
 * CGI entry point for php-cgi-wasm. Replaces the OpenSwoole server's route handlers.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 *
 * NOTE: php-cgi-wasm does not support exit/die - control flow uses if/elseif chains.
 */
require_once __DIR__ . '/bootstrap.php';

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';

// php-cgi-wasm sets REQUEST_URI from the Node.js rewrite
// For /orders, Node rewrites to /index.php/orders, so REQUEST_URI = /index.php/orders
$requestUri = $_SERVER['REQUEST_URI'] ?? '/';

// Strip /index.php prefix if present to get the clean path
$pathInfo = $requestUri;
if (strpos($pathInfo, '/index.php') === 0) {
    $pathInfo = substr($pathInfo, strlen('/index.php')) ?: '/';
}

// Strip query string from path if present
if (($qpos = strpos($pathInfo, '?')) !== false) {
    $pathInfo = substr($pathInfo, 0, $qpos);
}

// Normalize path
$pathInfo = rtrim($pathInfo, '/') ?: '/';

// Security headers
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: SAMEORIGIN');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('X-App-Name: {{APP_SLUG}}');

// CORS
$allowedOrigin = '{{CORS_ORIGIN}}';
header('Access-Control-Allow-Origin: ' . $allowedOrigin);

// Track whether a route was matched (php-cgi-wasm doesn't support exit/die)
$_handled = false;

// CORS preflight
if (!$_handled && $method === 'OPTIONS') {
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Authorization, X-API-Key');
    header('Access-Control-Max-Age: 86400');
    http_response_code(204);
    $_handled = true;
}

// Health check (always public)
if (!$_handled && $pathInfo === '{{HEALTH_PATH}}') {
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'ok',
        'app' => '{{APP_SLUG}}',
        'workspace' => '{{WORKSPACE}}',
        'runtime' => 'php-cgi-wasm',
    ]);
    $_handled = true;
}

if (!$_handled) {
    {{AUTH_HANDLER}}
}

// Route handling
if (!$_handled) {
    {{ROUTE_HANDLERS}}
}

// Default 404
if (!$_handled) {
    http_response_code(404);
    header('Content-Type: application/json');
    echo json_encode(['error' => 'Not found', 'path' => $pathInfo]);
}
