/**
 * WASM Tenant App Server - {{APP_NAME}}
 *
 * Node.js HTTP server wrapping php-cgi-wasm for portable PHP execution.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 */
import http from 'node:http';
import { PhpCgiNode } from 'php-cgi-wasm/PhpCgiNode.mjs';

const PORT = {{PORT}};
const APP_NAME = '{{APP_NAME}}';

/**
 * Parse CGI response from raw output bytes.
 * php-cgi-wasm alpha may throw even when PHP produces valid output.
 * This parser extracts headers + body from the STDOUT section of error output.
 */
function parseCgiOutput(rawText) {
    // Check if this is an error wrapper containing STDOUT
    const stdoutMatch = rawText.match(/STDOUT:\n([\s\S]*?)(?:\n={10,}|$)/);
    const text = stdoutMatch ? stdoutMatch[1] : rawText;

    // CGI output: headers\r\n\r\nbody
    const headerEnd = text.indexOf('\r\n\r\n');
    if (headerEnd === -1) {
        // Try LF-only separator
        const lfEnd = text.indexOf('\n\n');
        if (lfEnd === -1) {
            return { status: 200, headers: { 'Content-Type': 'text/html' }, body: text };
        }
        return parseCgiHeaders(text.substring(0, lfEnd), text.substring(lfEnd + 2));
    }
    return parseCgiHeaders(text.substring(0, headerEnd), text.substring(headerEnd + 4));
}

function parseCgiHeaders(headerBlock, body) {
    const headers = {};
    let status = 200;

    for (const line of headerBlock.split(/\r?\n/)) {
        const colon = line.indexOf(':');
        if (colon > 0) {
            const key = line.substring(0, colon).trim();
            const value = line.substring(colon + 1).trim();
            if (key.toLowerCase() === 'status') {
                status = parseInt(value, 10) || 200;
            } else if (key.toLowerCase() === 'x-powered-by') {
                // Skip X-Powered-By from PHP
                continue;
            } else {
                headers[key] = value;
            }
        }
    }

    return { status, headers, body };
}

const php = new PhpCgiNode({
    prefix: '/',
    docroot: '/www',
    persist: [
        { mountPath: '/www', localPath: './www' }
    ],
    sharedLibs: [
        await import('php-wasm-sqlite'),
    ],
});

const server = http.createServer(async (request, response) => {
    try {
        const url = new URL(request.url, `http://${request.headers.host}`);

        // Rewrite clean URLs to index.php with PATH_INFO
        if (!url.pathname.endsWith('.php') && url.pathname !== '/favicon.ico') {
            if (url.pathname === '/') {
                request.url = '/index.php';
            } else {
                request.url = `/index.php${url.pathname}${url.search}`;
            }
        }

        const result = await php.request(request);

        // Collect the full response body
        const reader = result.body.getReader();
        const chunks = [];
        let done = false;
        while (!done) {
            const chunk = await reader.read();
            done = chunk.done;
            if (chunk.value) chunks.push(chunk.value);
        }

        const bodyBuffer = Buffer.concat(chunks.map(c =>
            c instanceof Uint8Array ? Buffer.from(c) : Buffer.from(String(c))
        ));
        const bodyText = bodyBuffer.toString('utf-8');

        // Check if php-cgi-wasm returned an error wrapper with valid STDOUT
        if (result.status === 500 && bodyText.includes('STDOUT:')) {
            const parsed = parseCgiOutput(bodyText);
            response.writeHead(parsed.status, parsed.headers);
            response.end(parsed.body);
        } else {
            response.writeHead(result.status, Object.fromEntries(result.headers.entries()));
            response.end(bodyBuffer);
        }
    } catch (err) {
        console.error(`[${APP_NAME}] Request error:`, err.message);
        response.writeHead(500, { 'Content-Type': 'application/json' });
        response.end(JSON.stringify({ error: 'Internal server error', message: err.message }));
    }
});

server.listen(PORT, '127.0.0.1', () => {
    console.log(`[${APP_NAME}] WASM server running on http://127.0.0.1:${PORT}`);
});

process.on('SIGINT', () => {
    console.log(`[${APP_NAME}] Shutting down...`);
    server.close(() => process.exit(0));
});

process.on('SIGTERM', () => {
    console.log(`[${APP_NAME}] Shutting down...`);
    server.close(() => process.exit(0));
});
