#!/bin/bash
#
# schema-dump.sh - Dump current database schemas to SQL files
#
# Usage: ./scripts/schema-dump.sh [mysql|sqlite|both]
#
# This script dumps the current schema from working databases to create
# the authoritative SQL schema files. Run this after applying migrations
# to keep schema files in sync.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SQL_DIR="$PROJECT_DIR/sql"
CONFIG_FILE="$PROJECT_DIR/conf/config.ini"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=== Schema Dump Tool ==="
echo ""

# Parse config.ini for database settings
parse_ini() {
    local key=$1
    grep -E "^\s*$key\s*=" "$CONFIG_FILE" 2>/dev/null | sed 's/.*=\s*//' | tr -d '"' | tr -d "'"
}

# Dump MySQL schema
dump_mysql() {
    echo -e "${YELLOW}Dumping MySQL schema...${NC}"

    local db_host=$(parse_ini "db_host")
    local db_name=$(parse_ini "db_name")
    local db_user=$(parse_ini "db_user")
    local db_pass=$(parse_ini "db_pass")

    if [ -z "$db_name" ]; then
        echo -e "${RED}Error: Could not find MySQL config in $CONFIG_FILE${NC}"
        return 1
    fi

    local output_file="$SQL_DIR/mysql_schema.sql"

    # Build mysqldump command
    local cmd="mysqldump --no-data --skip-comments --compact"
    [ -n "$db_host" ] && cmd="$cmd -h $db_host"
    [ -n "$db_user" ] && cmd="$cmd -u $db_user"
    [ -n "$db_pass" ] && cmd="$cmd -p$db_pass"
    cmd="$cmd $db_name"

    # Add header
    cat > "$output_file" << 'EOF'
-- MyCTOBot MySQL Schema
-- Auto-generated by scripts/schema-dump.sh
-- Run this on a fresh MySQL database to set up the main application tables
--

EOF

    # Dump schema
    if $cmd >> "$output_file" 2>/dev/null; then
        echo -e "${GREEN}MySQL schema dumped to: $output_file${NC}"

        # Show table count
        local table_count=$(grep -c "CREATE TABLE" "$output_file" || echo "0")
        echo "  Tables: $table_count"
    else
        echo -e "${RED}Error: mysqldump failed. Check database credentials.${NC}"
        return 1
    fi
}

# Dump SQLite schema (from a representative user database)
dump_sqlite() {
    echo -e "${YELLOW}Dumping SQLite schema...${NC}"

    local db_path=$(parse_ini "user_db_path")
    [ -z "$db_path" ] && db_path="database/"

    # Find a non-empty SQLite database to use as template
    local template_db=""
    for db in "$PROJECT_DIR/$db_path"*.sqlite; do
        if [ -f "$db" ] && [ -s "$db" ]; then
            # Check if it has tables
            local tables=$(sqlite3 "$db" ".tables" 2>/dev/null)
            if [ -n "$tables" ]; then
                template_db="$db"
                break
            fi
        fi
    done

    if [ -z "$template_db" ]; then
        echo -e "${RED}Error: No suitable SQLite database found in $db_path${NC}"
        echo "  Need a database with tables to dump schema from."
        return 1
    fi

    echo "  Using template: $(basename "$template_db")"

    local output_file="$SQL_DIR/sqlite_schema.sql"

    # Add header
    cat > "$output_file" << 'EOF'
-- MyCTOBot Per-User SQLite Schema (Enterprise Tier)
-- Auto-generated by scripts/schema-dump.sh
-- Each user gets their own SQLite database: database/{ceobot_db}.sqlite
-- NOTE: All table names are lowercase with no underscores (RedBeanPHP requirement)
--

EOF

    # Dump schema (CREATE TABLE statements only, no data)
    sqlite3 "$template_db" << 'SQLITE_CMD' >> "$output_file"
.mode list
SELECT sql || ';' FROM sqlite_master
WHERE type='table' AND name NOT LIKE 'sqlite_%'
ORDER BY name;
SQLITE_CMD

    echo "" >> "$output_file"
    echo "-- Indexes" >> "$output_file"

    # Dump indexes
    sqlite3 "$template_db" << 'SQLITE_CMD' >> "$output_file"
.mode list
SELECT sql || ';' FROM sqlite_master
WHERE type='index' AND sql IS NOT NULL
ORDER BY name;
SQLITE_CMD

    # Clean up output (remove empty lines, fix formatting)
    sed -i 's/;;/;/g' "$output_file"
    sed -i '/^$/d' "$output_file"

    echo -e "${GREEN}SQLite schema dumped to: $output_file${NC}"

    # Show table count
    local table_count=$(grep -c "CREATE TABLE" "$output_file" || echo "0")
    local index_count=$(grep -c "CREATE INDEX" "$output_file" || echo "0")
    echo "  Tables: $table_count"
    echo "  Indexes: $index_count"
}

# Main
case "${1:-both}" in
    mysql)
        dump_mysql
        ;;
    sqlite)
        dump_sqlite
        ;;
    both)
        dump_mysql
        echo ""
        dump_sqlite
        ;;
    *)
        echo "Usage: $0 [mysql|sqlite|both]"
        echo ""
        echo "Options:"
        echo "  mysql   - Dump only MySQL schema"
        echo "  sqlite  - Dump only SQLite schema"
        echo "  both    - Dump both (default)"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}Done!${NC}"
echo ""
echo "Schema files are in: $SQL_DIR/"
ls -la "$SQL_DIR/"*.sql
