#!/bin/bash
#
# schema-dump.sh - Generate schema documentation from TenantSchemaBuilder
#
# Usage: ./scripts/schema-dump.sh [tenant|mysql|both]
#
# This script uses TenantSchemaBuilder.php as the source of truth for tenant
# database schemas. It creates a temporary database, runs the schema builder,
# then dumps the resulting schema.
#
# For MySQL (main app database), it dumps from the configured database.
#
# =============================================================================
# MIGRATION TOOL: scripts/run-migration.php
# =============================================================================
#
# To run schema migrations across tenants, use the migration tool:
#
#   # Show all available migrations
#   php scripts/run-migration.php --list
#
#   # Show all tenants
#   php scripts/run-migration.php --tenants
#
#   # Check migration status for all tenants
#   php scripts/run-migration.php --status
#
#   # Check status for specific tenant
#   php scripts/run-migration.php --status --tenant=gwt
#
#   # Run all pending migrations on all tenants
#   php scripts/run-migration.php --sync
#
#   # Run pending migrations on specific tenant
#   php scripts/run-migration.php --sync --tenant=gwt
#
#   # Run specific migration(s)
#   php scripts/run-migration.php --migration=SSHKeys
#   php scripts/run-migration.php --migration=SSHKeys,AIAgents,Member
#
#   # Force rebuild tables (drops and recreates - USE WITH CAUTION)
#   php scripts/run-migration.php --migration=all --force --tenant=footest4
#
#   # Mark migrations as applied without running (for existing DBs with data)
#   php scripts/run-migration.php --migration=all --mark --tenant=gwt
#
# =============================================================================
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SQL_DIR="$PROJECT_DIR/sql"
CONFIG_FILE="$PROJECT_DIR/conf/config.ini"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=== Schema Dump Tool ==="
echo "Source of truth: TenantSchemaBuilder.php"
echo ""

# Parse config.ini for database settings
parse_ini() {
    local key=$1
    grep -E "^\s*$key\s*=" "$CONFIG_FILE" 2>/dev/null | sed 's/.*=\s*//' | tr -d '"' | tr -d "'"
}

# Generate tenant schema from TenantSchemaBuilder
dump_tenant_schema() {
    echo -e "${YELLOW}Generating tenant schema from TenantSchemaBuilder...${NC}"

    # TenantSchemaBuilder creates MySQL schemas for tenants
    # We dump from an existing tenant database as reference
    # Find a tenant config to use - prefer gwt or tiknix which are known good
    local tenant_config=""
    for preferred in gwt tiknix; do
        if [ -f "$PROJECT_DIR/conf/config.$preferred.ini" ]; then
            tenant_config="$PROJECT_DIR/conf/config.$preferred.ini"
            break
        fi
    done

    # Fallback to any tenant config
    if [ -z "$tenant_config" ]; then
        tenant_config=$(ls "$PROJECT_DIR/conf/config."*.ini 2>/dev/null | grep -v 'config.ini$' | grep -v 'example' | head -1)
    fi

    if [ -z "$tenant_config" ]; then
        echo -e "${RED}Error: No tenant config found in conf/${NC}"
        return 1
    fi

    local tenant_name=$(basename "$tenant_config" | sed 's/config\.\(.*\)\.ini/\1/')
    echo "  Using tenant '$tenant_name' as reference"

    # Parse tenant database config (extract [database] section only)
    local db_section=$(sed -n '/^\[database\]/,/^\[/p' "$tenant_config" | head -n -1)
    local t_host=$(echo "$db_section" | grep -E '^\s*host\s*=' | sed 's/.*=\s*//' | tr -d '"' | tr -d "'" | head -1)
    local t_name=$(echo "$db_section" | grep -E '^\s*name\s*=' | sed 's/.*=\s*//' | tr -d '"' | tr -d "'" | head -1)
    local t_user=$(echo "$db_section" | grep -E '^\s*user\s*=' | sed 's/.*=\s*//' | tr -d '"' | tr -d "'" | head -1)
    local t_pass=$(echo "$db_section" | grep -E '^\s*pass\s*=' | sed 's/.*=\s*//' | tr -d '"' | tr -d "'" | head -1)

    if [ -z "$t_name" ]; then
        echo -e "${RED}Error: Could not parse tenant database config${NC}"
        return 1
    fi

    # Dump schema from tenant database (which was created by TenantSchemaBuilder)
    local output_file="$SQL_DIR/tenant_schema.sql"

    # Add header
    cat > "$output_file" << 'EOF'
-- MyCTOBot Tenant Database Schema
-- Auto-generated from TenantSchemaBuilder.php by scripts/schema-dump.sh
--
-- TenantSchemaBuilder.php is the SOURCE OF TRUTH for tenant schemas.
-- Do not edit this file directly - modify TenantSchemaBuilder.php instead.
--
-- Each tenant gets their own database (MySQL).
-- All table names are lowercase with no underscores (RedBeanPHP requirement).
--

EOF

    # Dump schema using mysqldump
    # Note: Password may contain special chars, so we use environment variable
    export MYSQL_PWD="$t_pass"
    if mysqldump --no-data --skip-comments -h "$t_host" -u "$t_user" "$t_name" >> "$output_file" 2>/dev/null; then
        unset MYSQL_PWD
        echo -e "${GREEN}Tenant schema dumped to: $output_file${NC}"

        # Show stats
        local table_count=$(grep -c "CREATE TABLE" "$output_file" || echo "0")
        echo "  Tables: $table_count"
    else
        # Try again, capture error
        local err=$(mysqldump --no-data --skip-comments -h "$t_host" -u "$t_user" "$t_name" 2>&1 >/dev/null)
        unset MYSQL_PWD

        # Check if we got data despite "error" (deprecation warnings cause this)
        if grep -q "CREATE TABLE" "$output_file" 2>/dev/null; then
            echo -e "${GREEN}Tenant schema dumped to: $output_file${NC}"
            local table_count=$(grep -c "CREATE TABLE" "$output_file" || echo "0")
            echo "  Tables: $table_count"
        else
            echo -e "${RED}Error: mysqldump failed for tenant database${NC}"
            echo "  $err"
            return 1
        fi
    fi

}

# Dump MySQL schema (main app database - not tenant)
dump_mysql() {
    echo -e "${YELLOW}Dumping MySQL schema (main app database)...${NC}"

    local db_host=$(parse_ini "db_host")
    local db_name=$(parse_ini "db_name")
    local db_user=$(parse_ini "db_user")
    local db_pass=$(parse_ini "db_pass")

    if [ -z "$db_name" ]; then
        echo -e "${RED}Error: Could not find MySQL config in $CONFIG_FILE${NC}"
        return 1
    fi

    local output_file="$SQL_DIR/mysql_schema.sql"

    # Build mysqldump command
    local cmd="mysqldump --no-data --skip-comments --compact"
    [ -n "$db_host" ] && cmd="$cmd -h $db_host"
    [ -n "$db_user" ] && cmd="$cmd -u $db_user"
    [ -n "$db_pass" ] && cmd="$cmd -p$db_pass"
    cmd="$cmd $db_name"

    # Add header
    cat > "$output_file" << 'EOF'
-- MyCTOBot MySQL Schema (Main Application Database)
-- Auto-generated by scripts/schema-dump.sh
--
-- This is the main application database schema (shared across all tenants).
-- Contains: members, atlassiantokens, claudeshards, etc.
--

EOF

    # Dump schema
    if $cmd >> "$output_file" 2>/dev/null; then
        echo -e "${GREEN}MySQL schema dumped to: $output_file${NC}"

        # Show table count
        local table_count=$(grep -c "CREATE TABLE" "$output_file" || echo "0")
        echo "  Tables: $table_count"
    else
        echo -e "${RED}Error: mysqldump failed. Check database credentials.${NC}"
        return 1
    fi
}

# Show help
show_help() {
    echo "Usage: $0 [tenant|mysql|both]"
    echo ""
    echo "Options:"
    echo "  tenant  - Generate tenant schema from TenantSchemaBuilder.php"
    echo "  mysql   - Dump main MySQL schema"
    echo "  both    - Generate both (default)"
    echo ""
    echo "The tenant schema is generated from TenantSchemaBuilder.php which is"
    echo "the source of truth. The MySQL schema is dumped from the live database."
    echo ""
    echo "MIGRATION TOOL:"
    echo "  To run migrations across tenants, use: php scripts/run-migration.php"
    echo ""
    echo "  Common commands:"
    echo "    --list                        List available migrations"
    echo "    --tenants                     List all tenants"
    echo "    --status                      Show migration status for all tenants"
    echo "    --sync                        Run pending migrations on all tenants"
    echo "    --sync --tenant=gwt           Run pending on specific tenant"
    echo "    --migration=SSHKeys           Run specific migration"
    echo "    --migration=all --force       Force rebuild all tables (DESTRUCTIVE)"
    echo "    --migration=all --mark        Mark as applied without running"
}

# Main
case "${1:-both}" in
    tenant)
        dump_tenant_schema
        ;;
    mysql)
        dump_mysql
        ;;
    both)
        dump_tenant_schema
        echo ""
        dump_mysql
        ;;
    -h|--help|help)
        show_help
        exit 0
        ;;
    *)
        show_help
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}Done!${NC}"
echo ""
echo "Schema files are in: $SQL_DIR/"
ls -la "$SQL_DIR/"*.sql 2>/dev/null || echo "No schema files found"
