<?php
/**
 * Tenant App Bootstrap - {{APP_NAME}}
 *
 * Minimal bootstrap for standalone app server.
 * Does NOT use Flight framework - direct service access only.
 *
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 */

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', '0');
ini_set('log_errors', '1');
ini_set('error_log', __DIR__ . '/storage/logs/php-errors.log');

// Timezone
date_default_timezone_set('America/New_York');

// Constants
define('APP_ROOT', __DIR__);
define('MYCTOBOT_ROOT', '{{MYCTOBOT_ROOT}}');

// Ensure storage directories exist
$storageDirs = [
    __DIR__ . '/storage',
    __DIR__ . '/storage/logs',
];

foreach ($storageDirs as $dir) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
}

// Register custom autoloader for app-specific classes
spl_autoload_register(function ($class) {
    // Handle app namespace
    if (str_starts_with($class, 'app\\')) {
        $file = MYCTOBOT_ROOT . '/' . str_replace('\\', '/', substr($class, 4)) . '.php';
        if (file_exists($file)) {
            require_once $file;
            return true;
        }

        // Try services directory
        $file = MYCTOBOT_ROOT . '/services/' . basename(str_replace('\\', '/', $class)) . '.php';
        if (file_exists($file)) {
            require_once $file;
            return true;
        }
    }

    return false;
});

// Load Bean wrapper class
require_once MYCTOBOT_ROOT . '/lib/Bean.php';

/**
 * Helper function to send JSON response
 */
function jsonResponse(\OpenSwoole\Http\Response $response, array $data, int $status = 200): void
{
    $response->status($status);
    $response->header('Content-Type', 'application/json');
    $response->end(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
}

/**
 * Helper function to parse JSON request body
 */
function parseJsonBody(\OpenSwoole\Http\Request $request): ?array
{
    // OpenSwoole uses getContent(), Swoole uses rawContent()
    $body = method_exists($request, 'getContent') ? $request->getContent() : $request->rawContent();
    if (empty($body)) {
        return null;
    }

    $data = json_decode($body, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        return null;
    }

    return $data;
}

/**
 * Helper function to get bearer token from request
 */
function getBearerToken(\OpenSwoole\Http\Request $request): ?string
{
    $auth = $request->header['authorization'] ?? '';
    if (str_starts_with($auth, 'Bearer ')) {
        return substr($auth, 7);
    }
    return null;
}

/**
 * Helper function to get API key from request
 */
function getApiKey(\OpenSwoole\Http\Request $request): ?string
{
    // Check X-API-Key header first
    $apiKey = $request->header['x-api-key'] ?? null;
    if ($apiKey) {
        return $apiKey;
    }

    // Check query parameter
    $query = [];
    parse_str($request->server['query_string'] ?? '', $query);
    return $query['api_key'] ?? null;
}
