<?php
/**
 * Tenant App Configuration - {{APP_NAME}}
 *
 * Auto-generated configuration for tenant app.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 */

return [
    // Server settings
    'host' => '{{HOST}}',
    'port' => {{PORT}},
    'workers' => {{WORKERS}},

    // App metadata
    'app_id' => {{APP_ID}},
    'app_name' => '{{APP_NAME}}',
    'app_slug' => '{{APP_SLUG}}',
    'workspace' => '{{WORKSPACE}}',

    // Authentication
    'auth_type' => '{{AUTH_TYPE}}',
    'api_key' => '{{API_KEY}}',

    // Pipeline integration
    'pipeline_id' => {{PIPELINE_ID}},
    'app_type' => '{{APP_TYPE}}',

    // Debug mode
    'debug' => {{DEBUG}},

    // Custom routes
    'routes' => {{ROUTES_JSON}},

    // MCP exposure
    'expose_mcp' => {{EXPOSE_MCP}},
    'mcp_tools' => {{MCP_TOOLS_JSON}},
];
