<?php
declare(strict_types=1);
/**
 * Tenant App Server - {{APP_NAME}}
 *
 * Auto-generated OpenSwoole HTTP server for tenant app.
 * Workspace: {{WORKSPACE}}
 * Generated: {{GENERATED_AT}}
 *
 * DO NOT EDIT - This file is auto-generated by TenantAppBuilder
 */

// Use main MyCTOBot vendor (no duplication)
require_once '{{MYCTOBOT_ROOT}}/vendor/autoload.php';
require_once __DIR__ . '/bootstrap.php';

use OpenSwoole\Http\Server;
use OpenSwoole\Http\Request;
use OpenSwoole\Http\Response;
use app\services\TenantAppDatabase;
use app\services\TenantAppLogger;
use app\services\PipelineExecutor;
use app\Bean;

{{HELPER_FUNCTIONS}}

$config = require __DIR__ . '/config.php';

// Initialize logger
$logger = new TenantAppLogger('{{WORKSPACE}}', '{{APP_SLUG}}', true);
$logger->info('Starting app server on port {port}', ['port' => $config['port']]);

// Initialize database for this workspace
TenantAppDatabase::init('{{WORKSPACE}}');

$server = new Server($config['host'], $config['port']);
$server->set([
    'worker_num' => $config['workers'],
    'log_file' => __DIR__ . '/storage/logs/swoole.log',
    'pid_file' => __DIR__ . '/storage/app.pid',
    'daemonize' => false,  // Managed by tmux
    'max_request' => 10000,
    'dispatch_mode' => 2,
]);

// Rate limiting storage (100 req/min per IP)
$requests = [];

$server->on('start', function($server) use ($config, $logger) {
    file_put_contents(__DIR__ . '/storage/app.pid', $server->master_pid);
    $logger->info('Server started successfully', [
        'host' => $config['host'],
        'port' => $config['port'],
        'workers' => $config['workers'],
        'pid' => $server->master_pid,
    ]);
    echo "[{{APP_NAME}}] Server started on http://{$config['host']}:{$config['port']}\n";
});

$server->on('workerStart', function($server, $workerId) use ($logger) {
    // Re-initialize database connection for this worker
    TenantAppDatabase::init('{{WORKSPACE}}');
    $logger->debug('Worker started', ['worker_id' => $workerId]);
});

$server->on('request', function(Request $request, Response $response) use ($config, $logger, &$requests) {
    $startTime = microtime(true);

    // Set default headers
    $response->header('Content-Type', 'application/json');
    $response->header('X-App-Name', '{{APP_SLUG}}');
    $response->header('X-Content-Type-Options', 'nosniff');
    $response->header('X-Frame-Options', 'SAMEORIGIN');
    $response->header('Referrer-Policy', 'strict-origin-when-cross-origin');

    // CORS - use configured origin or restrict to same origin
    $allowedOrigin = $config['cors_origin'] ?? '*';
    $response->header('Access-Control-Allow-Origin', $allowedOrigin);

    // Handle CORS preflight
    if ($request->server['request_method'] === 'OPTIONS') {
        $response->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
        $response->header('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-API-Key');
        $response->header('Access-Control-Max-Age', '86400');
        $response->end('');
        return;
    }

    $path = $request->server['request_uri'] ?? '/';
    $method = $request->server['request_method'] ?? 'GET';
    $ip = $request->server['remote_addr'] ?? 'unknown';

    // Health check endpoint (always public, no rate limiting)
    if ($path === '{{HEALTH_PATH}}') {
        $response->end(json_encode([
            'status' => 'ok',
            'app' => '{{APP_SLUG}}',
            'workspace' => '{{WORKSPACE}}',
            'uptime' => time() - (int)(filemtime(__DIR__ . '/storage/app.pid') ?: time()),
        ]));
        return;
    }

    // Rate limiting
    $now = time();
    $requests[$ip] = array_filter($requests[$ip] ?? [], fn($t) => $t > $now - 60);
    $requests[$ip][] = $now;

    if (count($requests[$ip]) > 100) {
        $logger->warning('Rate limited request', ['ip' => $ip, 'path' => $path]);
        $response->status(429);
        $response->end(json_encode([
            'error' => 'Rate limited',
            'message' => 'Too many requests. Please wait before trying again.',
        ]));
        return;
    }

    // Authentication
    {{AUTH_HANDLER}}

    // Route handling
    try {
        {{ROUTE_HANDLERS}}

        // Default 404
        $logger->debug('Route not found', ['path' => $path, 'method' => $method]);
        $response->status(404);
        $response->end(json_encode([
            'error' => 'Not found',
            'path' => $path,
        ]));

    } catch (\Throwable $e) {
        $logger->error('Request error: {message}', [
            'message' => $e->getMessage(),
            'path' => $path,
            'trace' => $e->getTraceAsString(),
        ]);

        $response->status(500);
        $response->end(json_encode([
            'error' => 'Internal server error',
            'message' => $config['debug'] ? $e->getMessage() : 'An error occurred',
        ]));
    }

    // Log request completion
    $duration = round((microtime(true) - $startTime) * 1000, 2);
    $logger->debug('Request completed', [
        'method' => $method,
        'path' => $path,
        'duration_ms' => $duration,
        'ip' => $ip,
    ]);
});

$server->on('shutdown', function($server) use ($logger) {
    $logger->info('Server shutting down');
    @unlink(__DIR__ . '/storage/app.pid');
});

$server->start();
