# {{APP_NAME}} Configuration
# Generated by MyCTOBot Detachable App Builder

# MyCTOBot API endpoint (do not change unless self-hosting)
MYCTOBOT_API_URL={{DEFAULT_API_URL}}

# API token for pipeline proxy (starts with tk_)
MYCTOBOT_API_TOKEN=tk_your_token_here

# Workspace slug
MYCTOBOT_WORKSPACE={{WORKSPACE}}

# Local port (change if running multiple apps)
APP_PORT=8080
