# Detachable App: {{APP_NAME}}
# Generated by MyCTOBot Detachable App Builder
# Workspace: {{WORKSPACE}}

FROM php:8.2-fpm-alpine AS php-base

RUN docker-php-ext-install curl

COPY php/ /var/www/php/

FROM nginx:alpine

# Copy PHP-FPM binary and libraries from build stage
COPY --from=php-base /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm
COPY --from=php-base /usr/local/lib/php/ /usr/local/lib/php/
COPY --from=php-base /usr/local/etc/ /usr/local/etc/
COPY --from=php-base /var/www/php/ /var/www/php/

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy entrypoint
COPY docker-entrypoint.sh /docker-entrypoint.sh

# Copy static assets and screens
COPY public/ /var/www/html/

RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

CMD ["/docker-entrypoint.sh"]
