# {{APP_NAME}} - Detachable App
# Generated by MyCTOBot Detachable App Builder
# Workspace: {{WORKSPACE}}

version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:80"
    env_file:
      - .env
    restart: unless-stopped
