-- MyCTOBot Per-User SQLite Schema (Enterprise Tier)
-- Auto-generated by scripts/schema-dump.sh
-- Each user gets their own SQLite database: database/{ceobot_db}.sqlite
-- NOTE: All table names are lowercase with no underscores (RedBeanPHP requirement)
--
CREATE TABLE "aidevjoblogs" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    issue_key TEXT NOT NULL,
    log_level TEXT DEFAULT 'info',
    message TEXT NOT NULL,
    context_json TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "aidevjobs" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    issue_key TEXT NOT NULL UNIQUE,
    board_id INTEGER NOT NULL,
    repo_connection_id INTEGER,
    cloud_id TEXT,
    status TEXT DEFAULT 'pending',
    current_shard_job_id TEXT,
    branch_name TEXT,
    pr_url TEXT,
    pr_number INTEGER,
    clarification_comment_id TEXT,
    clarification_questions TEXT,
    error_message TEXT,
    run_count INTEGER DEFAULT 0,
    last_output TEXT,
    last_result_json TEXT,
    files_changed TEXT,
    commit_sha TEXT,
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT
);
CREATE TABLE "analysisresults" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER NOT NULL,
    analysis_type TEXT NOT NULL,
    content_json TEXT NOT NULL,
    content_markdown TEXT,
    issue_count INTEGER,
    status_filter TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (board_id) REFERENCES "jiraboards"(id) ON DELETE CASCADE
);
CREATE TABLE "boardrepomapping" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER NOT NULL,
    repo_connection_id INTEGER NOT NULL,
    is_default INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (board_id) REFERENCES "jiraboards"(id) ON DELETE CASCADE,
    FOREIGN KEY (repo_connection_id) REFERENCES "repoconnections"(id) ON DELETE CASCADE
);
CREATE TABLE "digesthistory" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER NOT NULL,
    sent_to TEXT NOT NULL,
    subject TEXT,
    content_preview TEXT,
    status TEXT DEFAULT 'sent',
    error_message TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (board_id) REFERENCES "jiraboards"(id) ON DELETE CASCADE
);
CREATE TABLE `enterprisesettings` ( id INTEGER PRIMARY KEY AUTOINCREMENT , `setting_key` TEXT, `created_at` NUMERIC, `setting_value` TEXT, `is_encrypted` INTEGER, `updated_at` NUMERIC);
CREATE TABLE "jiraboards" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER NOT NULL,
    board_name TEXT NOT NULL,
    project_key TEXT NOT NULL,
    cloud_id TEXT NOT NULL,
    board_type TEXT DEFAULT 'scrum',
    enabled INTEGER DEFAULT 1,
    digest_enabled INTEGER DEFAULT 0,
    digest_time TEXT DEFAULT '08:00',
    digest_cc TEXT DEFAULT '',
    timezone TEXT DEFAULT 'UTC',
    status_filter TEXT DEFAULT 'To Do',
    priority_weights TEXT,
    goals TEXT,
    last_analysis_at TEXT,
    last_digest_at TEXT,
    -- AI Developer status transition settings (per-board)
    -- Store the target status NAME (not ID) - we'll look up transition ID at runtime
    aidev_status_working TEXT DEFAULT NULL,      -- Status when AI starts working (e.g., "In Progress")
    aidev_status_pr_created TEXT DEFAULT NULL,   -- Status when PR is created (e.g., "Ready for QA")
    aidev_status_clarification TEXT DEFAULT NULL, -- Status when clarification needed (e.g., "Blocked")
    aidev_status_failed TEXT DEFAULT NULL,       -- Status on failure (null = don't change)
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    UNIQUE(board_id, cloud_id)
);
CREATE TABLE "repoconnections" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    connection_name TEXT,
    provider TEXT DEFAULT 'github',
    repo_owner TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    default_branch TEXT DEFAULT 'main',
    clone_url TEXT,
    access_token TEXT,
    enabled INTEGER DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT
);
CREATE TABLE "ticketanalysiscache" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER NOT NULL,
    issue_key TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    clarity_score INTEGER,
    clarity_analysis TEXT,
    reporter_name TEXT,
    reporter_email TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    UNIQUE(board_id, issue_key),
    FOREIGN KEY (board_id) REFERENCES "jiraboards"(id) ON DELETE CASCADE
);
CREATE TABLE "usersettings" (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
-- Indexes
CREATE INDEX idx_aidevjoblogs_issue ON aidevjoblogs(issue_key);
CREATE INDEX idx_aidevjobs_board ON aidevjobs(board_id);
CREATE INDEX idx_aidevjobs_issue ON aidevjobs(issue_key);
CREATE INDEX idx_aidevjobs_status ON aidevjobs(status);
CREATE INDEX idx_analysis_board ON "analysisresults"(board_id);
CREATE INDEX idx_analysis_created ON "analysisresults"(created_at DESC);
CREATE INDEX idx_analysis_type ON "analysisresults"(analysis_type);
CREATE INDEX idx_boardrepomapping_board ON boardrepomapping(board_id);
CREATE INDEX idx_boards_cloud ON "jiraboards"(cloud_id);
CREATE INDEX idx_boards_digest ON "jiraboards"(digest_enabled);
CREATE INDEX idx_boards_enabled ON "jiraboards"(enabled);
CREATE INDEX idx_digest_board ON "digesthistory"(board_id);
CREATE INDEX idx_digest_created ON "digesthistory"(created_at DESC);
CREATE INDEX idx_enterprisesettings_key ON enterprisesettings(setting_key);
CREATE INDEX idx_ticket_cache_board ON "ticketanalysiscache"(board_id);
CREATE INDEX idx_ticket_cache_hash ON "ticketanalysiscache"(content_hash);
