-- MyCTOBot Tenant Database Schema
-- Auto-generated from TenantSchemaBuilder.php by scripts/schema-dump.sh
--
-- TenantSchemaBuilder.php is the SOURCE OF TRUTH for tenant schemas.
-- Do not edit this file directly - modify TenantSchemaBuilder.php instead.
--
-- Each tenant gets their own database (MySQL).
-- All table names are lowercase with no underscores (RedBeanPHP requirement).
--

/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;
DROP TABLE IF EXISTS `aiagents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `aiagents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) DEFAULT NULL,
  `created_by_member_id` int(11) DEFAULT NULL,
  `created_by_name` varchar(255) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `runner_type` varchar(50) NOT NULL DEFAULT 'claude_cli',
  `runner_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`runner_config`)),
  `mcp_servers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`mcp_servers`)),
  `hooks_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`hooks_config`)),
  `is_active` tinyint(1) DEFAULT 1,
  `is_default` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_member_id` (`member_id`),
  KEY `idx_active` (`is_active`),
  KEY `idx_default` (`is_default`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `aidevjoblogs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `aidevjoblogs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `issue_key` varchar(50) NOT NULL,
  `log_level` varchar(20) DEFAULT 'info',
  `message` text NOT NULL,
  `context_json` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_issue` (`issue_key`)
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `aidevjobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `aidevjobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_uid` varchar(64) NOT NULL,
  `member_id` int(11) NOT NULL,
  `issue_key` varchar(50) NOT NULL,
  `board_id` int(11) NOT NULL,
  `repo_connection_id` int(11) DEFAULT NULL,
  `cloud_uid` varchar(100) DEFAULT NULL,
  `status` varchar(30) DEFAULT 'pending',
  `progress` int(11) DEFAULT 0,
  `current_step` varchar(100) DEFAULT 'Initializing',
  `steps_completed` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`steps_completed`)),
  `current_shard_job_uid` varchar(64) DEFAULT NULL,
  `branch_name` varchar(255) DEFAULT NULL,
  `pr_url` varchar(500) DEFAULT NULL,
  `pr_number` int(11) DEFAULT NULL,
  `pr_created_at` datetime DEFAULT NULL,
  `clarification_comment_uid` varchar(50) DEFAULT NULL,
  `clarification_questions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`clarification_questions`)),
  `error_message` text DEFAULT NULL,
  `run_count` int(11) DEFAULT 0,
  `last_output` longtext DEFAULT NULL,
  `last_result_json` longtext DEFAULT NULL,
  `files_changed` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`files_changed`)),
  `commit_sha` varchar(64) DEFAULT NULL,
  `shopify_theme_id` int(11) DEFAULT NULL,
  `shopify_preview_url` varchar(500) DEFAULT NULL,
  `playwright_results` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`playwright_results`)),
  `preserve_branch` tinyint(1) DEFAULT 1,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `project_type` varchar(191) DEFAULT NULL,
  `repo_id` int(11) unsigned DEFAULT NULL,
  `queue_metadata` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_job_uid` (`job_uid`),
  KEY `idx_member` (`member_id`),
  KEY `idx_board` (`board_id`),
  KEY `idx_status` (`status`),
  KEY `idx_issue` (`issue_key`),
  KEY `idx_member_issue` (`member_id`,`issue_key`),
  KEY `index_foreignkey_aidevjobs_repo` (`repo_id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `analysisresults`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `analysisresults` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `board_id` int(11) unsigned DEFAULT NULL,
  `analysis_type` varchar(191) DEFAULT NULL,
  `content_json` text DEFAULT NULL,
  `content_markdown` text DEFAULT NULL,
  `issue_count` int(11) unsigned DEFAULT NULL,
  `status_filter` varchar(191) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_analysisresults_board` (`board_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `anthropickeys`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `anthropickeys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by_member_id` int(11) NOT NULL,
  `created_by_name` varchar(255) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `api_key` text NOT NULL,
  `model` varchar(100) DEFAULT 'claude-sonnet-4-20250514',
  `shared` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_member` (`created_by_member_id`),
  KEY `idx_shared` (`shared`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `atlassiantoken`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `atlassiantoken` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) NOT NULL,
  `access_token` text NOT NULL,
  `refresh_token` text NOT NULL,
  `token_type` varchar(50) DEFAULT 'Bearer',
  `expires_at` datetime NOT NULL,
  `cloud_uid` varchar(100) NOT NULL,
  `site_url` varchar(500) DEFAULT NULL,
  `site_name` varchar(255) DEFAULT NULL,
  `scopes` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_member_id` (`member_id`),
  KEY `idx_expires_at` (`expires_at`),
  CONSTRAINT `atlassiantoken_ibfk_1` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `authcontrol`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `authcontrol` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `control` varchar(100) NOT NULL,
  `method` varchar(100) NOT NULL,
  `level` int(11) NOT NULL DEFAULT 100,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `validcount` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_control_method` (`control`,`method`)
) ENGINE=InnoDB AUTO_INCREMENT=203 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `boardrepomapping`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `boardrepomapping` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `board_id` int(11) unsigned DEFAULT NULL,
  `repo_connection_id` int(11) unsigned DEFAULT NULL,
  `is_default` tinyint(1) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `jiraboards_id` int(11) unsigned DEFAULT NULL,
  `repoconnections_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_boardrepomapping_board` (`board_id`),
  KEY `index_foreignkey_boardrepomapping_repo_connection` (`repo_connection_id`),
  KEY `index_foreignkey_boardrepomapping_jiraboards` (`jiraboards_id`),
  KEY `index_foreignkey_boardrepomapping_repoconnections` (`repoconnections_id`),
  CONSTRAINT `c_fk_boardrepomapping_jiraboards_id` FOREIGN KEY (`jiraboards_id`) REFERENCES `jiraboards` (`id`) ON DELETE SET NULL ON UPDATE SET NULL,
  CONSTRAINT `c_fk_boardrepomapping_repoconnections_id` FOREIGN KEY (`repoconnections_id`) REFERENCES `repoconnections` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ceodirectivelogs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ceodirectivelogs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `directive_id` varchar(191) DEFAULT NULL,
  `member_id` int(11) unsigned DEFAULT NULL,
  `issue_key` varchar(191) DEFAULT NULL,
  `action` varchar(191) DEFAULT NULL,
  `message` varchar(191) DEFAULT NULL,
  `context_json` varchar(191) DEFAULT NULL,
  `stack_trace` text DEFAULT NULL,
  `recovery_action` varchar(191) DEFAULT NULL,
  `response_content` tinyint(1) unsigned DEFAULT NULL,
  `delivery_status` tinyint(1) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `directive_uid` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_ceodirectivelogs_directive` (`directive_id`),
  KEY `index_foreignkey_ceodirectivelogs_member` (`member_id`)
) ENGINE=InnoDB AUTO_INCREMENT=608 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ceodirectives`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ceodirectives` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `directive_uid` varchar(64) NOT NULL,
  `member_id` int(11) NOT NULL,
  `email_from` varchar(255) DEFAULT NULL,
  `email_subject` varchar(500) DEFAULT NULL,
  `email_body` text DEFAULT NULL,
  `email_message_uid` varchar(255) DEFAULT NULL,
  `parsed_intent` enum('project','feature','bug','question','report') DEFAULT 'project',
  `parsed_summary` text DEFAULT NULL,
  `parsed_requirements` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`parsed_requirements`)),
  `status` enum('received','parsing','planning','executing','completed','failed') DEFAULT 'received',
  `current_phase` varchar(50) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `approval_mode` enum('auto','manual') DEFAULT 'auto',
  `project_id` int(11) DEFAULT NULL,
  `response_sent_at` datetime DEFAULT NULL,
  `response_content` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directive_id` (`directive_uid`),
  KEY `idx_status` (`status`),
  KEY `idx_member` (`member_id`),
  KEY `idx_directive_id` (`directive_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `claudeshards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `claudeshards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `host` varchar(255) NOT NULL,
  `port` int(11) DEFAULT 3500,
  `api_key` varchar(255) NOT NULL,
  `shard_type` enum('general','playwright','database','full','custom') DEFAULT 'general',
  `capabilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`capabilities`)),
  `max_concurrent_jobs` int(11) DEFAULT 2,
  `is_active` tinyint(1) DEFAULT 1,
  `is_default` tinyint(1) DEFAULT 0,
  `last_health_check` datetime DEFAULT NULL,
  `health_status` enum('healthy','unhealthy','unknown') DEFAULT 'unknown',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `execution_mode` varchar(191) DEFAULT NULL,
  `ssh_user` varchar(191) DEFAULT NULL,
  `ssh_port` int(11) unsigned DEFAULT NULL,
  `ssh_key_path` tinyint(1) unsigned DEFAULT NULL,
  `ssh_validated` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_host_port` (`host`,`port`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ctoepics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ctoepics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `epic_id` varchar(32) NOT NULL,
  `project_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `acceptance_criteria` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`acceptance_criteria`)),
  `jira_epic_key` varchar(50) DEFAULT NULL,
  `jira_epic_id` varchar(50) DEFAULT NULL,
  `status` enum('backlog','in_progress','review','completed') DEFAULT 'backlog',
  `story_count` int(11) DEFAULT 0,
  `stories_completed` int(11) DEFAULT 0,
  `priority` int(11) DEFAULT 0,
  `sequence` int(11) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `epic_id` (`epic_id`),
  KEY `idx_project` (`project_id`),
  KEY `idx_status` (`status`),
  KEY `idx_epic_id` (`epic_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ctoprojects`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ctoprojects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_uid` varchar(64) NOT NULL,
  `directive_id` int(11) DEFAULT NULL,
  `member_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `goals` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`goals`)),
  `estimated_effort` varchar(50) DEFAULT NULL,
  `risk_assessment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`risk_assessment`)),
  `tech_stack` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tech_stack`)),
  `jira_project_key` varchar(50) DEFAULT NULL,
  `board_id` int(11) DEFAULT NULL,
  `github_repo_id` int(11) DEFAULT NULL,
  `status` enum('planning','in_progress','blocked','completed','cancelled') DEFAULT 'planning',
  `completion_percentage` int(11) DEFAULT 0,
  `milestones` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`milestones`)),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `project_id` (`project_uid`),
  KEY `idx_status` (`status`),
  KEY `idx_directive` (`directive_id`),
  KEY `idx_project_id` (`project_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ctostories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ctostories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `story_id` varchar(32) NOT NULL,
  `epic_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `acceptance_criteria` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`acceptance_criteria`)),
  `story_points` int(11) DEFAULT NULL,
  `jira_issue_key` varchar(50) DEFAULT NULL,
  `jira_issue_id` varchar(50) DEFAULT NULL,
  `aidev_job_id` varchar(64) DEFAULT NULL,
  `status` enum('backlog','ready','in_progress','review','done','blocked') DEFAULT 'backlog',
  `blocker_reason` text DEFAULT NULL,
  `depends_on` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`depends_on`)),
  `verified_at` datetime DEFAULT NULL,
  `verification_result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`verification_result`)),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `story_id` (`story_id`),
  KEY `idx_epic` (`epic_id`),
  KEY `idx_jira` (`jira_issue_key`),
  KEY `idx_status` (`status`),
  KEY `idx_story_id` (`story_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `digesthistory`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `digesthistory` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `board_id` int(11) unsigned DEFAULT NULL,
  `sent_to` varchar(191) DEFAULT NULL,
  `subject` varchar(191) DEFAULT NULL,
  `content_preview` text DEFAULT NULL,
  `status` varchar(191) DEFAULT NULL,
  `error_message` tinyint(1) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_digesthistory_board` (`board_id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `digestjobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `digestjobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` varchar(64) NOT NULL,
  `member_id` int(11) NOT NULL,
  `board_id` int(11) NOT NULL,
  `board_name` varchar(255) DEFAULT NULL,
  `project_key` varchar(50) DEFAULT NULL,
  `status` enum('queued','pending','running','completed','failed') DEFAULT 'queued',
  `send_email` tinyint(1) DEFAULT 1,
  `digest_cc` text DEFAULT NULL,
  `result` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result`)),
  `error` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `shard_id` int(11) unsigned DEFAULT NULL,
  `items_count` tinyint(1) unsigned DEFAULT NULL,
  `phase` varchar(191) DEFAULT NULL,
  `elapsed_seconds` int(11) unsigned DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `partial_output` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_id` (`job_id`),
  KEY `idx_member_status` (`member_id`,`status`),
  KEY `idx_job_id` (`job_id`),
  KEY `index_foreignkey_digestjobs_shard` (`shard_id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `directivelogs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `directivelogs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `directive_id` varchar(32) NOT NULL,
  `phase` varchar(50) NOT NULL,
  `log_level` enum('info','warning','error') DEFAULT 'info',
  `message` text NOT NULL,
  `context_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`context_json`)),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_directive` (`directive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `enterprisesettings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `enterprisesettings` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(191) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `setting_value` text DEFAULT NULL,
  `is_encrypted` tinyint(1) unsigned DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `member_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_enterprisesettings_member` (`member_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `jiraboards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `jiraboards` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `board_id` int(11) unsigned DEFAULT NULL,
  `board_name` varchar(191) DEFAULT NULL,
  `project_key` varchar(191) DEFAULT NULL,
  `cloud_uid` varchar(100) DEFAULT NULL,
  `board_type` varchar(191) DEFAULT NULL,
  `enabled` tinyint(1) unsigned DEFAULT NULL,
  `digest_enabled` tinyint(1) unsigned DEFAULT NULL,
  `digest_time` varchar(191) DEFAULT NULL,
  `digest_cc` varchar(191) DEFAULT NULL,
  `timezone` varchar(191) DEFAULT NULL,
  `status_filter` varchar(191) DEFAULT NULL,
  `priority_weights` varchar(255) DEFAULT NULL,
  `goals` varchar(191) DEFAULT NULL,
  `last_analysis_at` datetime DEFAULT NULL,
  `last_digest_at` datetime DEFAULT NULL,
  `aidev_status_working` varchar(191) DEFAULT NULL,
  `aidev_status_pr_created` varchar(191) DEFAULT NULL,
  `aidev_status_clarification` varchar(191) DEFAULT NULL,
  `aidev_status_failed` varchar(191) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `aidev_status_complete` varchar(191) DEFAULT NULL,
  `aidev_anthropic_key_id` int(11) unsigned DEFAULT NULL,
  `member_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_jiraboards_board` (`board_id`),
  KEY `index_foreignkey_jiraboards_cloud` (`cloud_uid`),
  KEY `index_foreignkey_jiraboards_aidev_anthropic_key` (`aidev_anthropic_key_id`),
  KEY `index_foreignkey_jiraboards_member` (`member_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `member`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `google_id` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `avatar_url` text DEFAULT NULL,
  `level` int(11) NOT NULL DEFAULT 100,
  `status` enum('active','inactive','pending','system') DEFAULT 'active',
  `ceobot_db` varchar(64) DEFAULT NULL,
  `email_verified` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `last_login` datetime DEFAULT NULL,
  `login_count` int(11) DEFAULT 0,
  `reset_token` varchar(64) DEFAULT NULL,
  `reset_expires` datetime DEFAULT NULL,
  `first_name` varchar(191) DEFAULT NULL,
  `last_name` varchar(191) DEFAULT NULL,
  `bio` varchar(191) DEFAULT NULL,
  `invite_token` varchar(191) DEFAULT NULL,
  `invite_sent_at` datetime DEFAULT NULL,
  `invite_expires_at` datetime DEFAULT NULL,
  `invited_by` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `google_id` (`google_id`),
  KEY `idx_google_id` (`google_id`),
  KEY `idx_email` (`email`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `repoconnections`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `repoconnections` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `connection_name` varchar(191) DEFAULT NULL,
  `provider` varchar(191) DEFAULT NULL,
  `repo_owner` varchar(191) DEFAULT NULL,
  `repo_name` varchar(191) DEFAULT NULL,
  `default_branch` varchar(191) DEFAULT NULL,
  `clone_url` varchar(191) DEFAULT NULL,
  `access_token` varchar(191) DEFAULT NULL,
  `enabled` tinyint(1) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `member_id` int(11) DEFAULT NULL,
  `created_by_member_id` int(11) DEFAULT NULL,
  `created_by_name` varchar(255) DEFAULT NULL,
  `aiagents_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_repoconnections_member` (`member_id`),
  KEY `index_foreignkey_repoconnections_agent` (`aiagents_id`),
  KEY `idx_aiagents` (`aiagents_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) DEFAULT NULL,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_key` (`member_id`,`setting_key`),
  CONSTRAINT `settings_ibfk_1` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `shardassignments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shardassignments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) NOT NULL,
  `shard_id` int(11) NOT NULL,
  `priority` int(11) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_member_shard` (`member_id`,`shard_id`),
  KEY `shard_id` (`shard_id`),
  CONSTRAINT `shardassignments_ibfk_1` FOREIGN KEY (`shard_id`) REFERENCES `claudeshards` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `shardjobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shardjobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` varchar(64) NOT NULL,
  `member_id` int(11) NOT NULL,
  `shard_id` int(11) NOT NULL,
  `issue_key` varchar(50) DEFAULT NULL,
  `status` enum('queued','running','completed','failed','cancelled') DEFAULT 'queued',
  `request_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`request_payload`)),
  `result_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result_payload`)),
  `error_message` text DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_id` (`job_id`),
  KEY `idx_member_status` (`member_id`,`status`),
  KEY `idx_shard_status` (`shard_id`,`status`),
  CONSTRAINT `shardjobs_ibfk_1` FOREIGN KEY (`shard_id`) REFERENCES `claudeshards` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `shopifyconnections`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shopifyconnections` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created_by_member_id` int(11) unsigned DEFAULT NULL,
  `created_by_name` varchar(191) DEFAULT NULL,
  `connection_name` varchar(191) DEFAULT NULL,
  `shop_domain` varchar(191) DEFAULT NULL,
  `access_token` varchar(191) DEFAULT NULL,
  `enabled` tinyint(1) unsigned DEFAULT NULL,
  `shared` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `shop_name` varchar(191) DEFAULT NULL,
  `shop_email` varchar(191) DEFAULT NULL,
  `repo_connection_id` int(11) unsigned DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_shopifyconnections_created_by_member` (`created_by_member_id`),
  KEY `index_foreignkey_shopifyconnections_repo_connection` (`repo_connection_id`),
  KEY `idx_member` (`created_by_member_id`),
  KEY `idx_shared` (`shared`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `subscription`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `subscription` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) DEFAULT NULL,
  `billing_email` varchar(255) DEFAULT NULL,
  `billing_name` varchar(255) DEFAULT NULL,
  `tier` varchar(20) NOT NULL DEFAULT 'free',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `stripe_customer_id` varchar(255) DEFAULT NULL,
  `stripe_subscription_id` varchar(255) DEFAULT NULL,
  `current_period_start` datetime DEFAULT NULL,
  `current_period_end` datetime DEFAULT NULL,
  `trial_ends_at` datetime DEFAULT NULL,
  `cancelled_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `trial_used` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_subscription_tier` (`tier`),
  KEY `idx_subscription_status` (`status`),
  KEY `idx_subscription_active` (`status`,`tier`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `system_settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `system_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `test_discoveredplugins`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `test_discoveredplugins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_id` varchar(64) NOT NULL,
  `repo_connection_id` int(11) NOT NULL,
  `repo_owner` varchar(100) NOT NULL,
  `repo_name` varchar(100) NOT NULL,
  `plugin_name` varchar(255) DEFAULT NULL,
  `plugin_description` text DEFAULT NULL,
  `plugin_version` varchar(50) DEFAULT NULL,
  `plugin_author` varchar(255) DEFAULT NULL,
  `plugin_main` varchar(500) DEFAULT NULL,
  `plugin_requires` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`plugin_requires`)),
  `plugin_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`plugin_json`)),
  `status` enum('discovered','validated','invalid','installed') DEFAULT 'discovered',
  `validation_error` text DEFAULT NULL,
  `discovered_at` datetime DEFAULT current_timestamp(),
  `last_scanned_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `plugin_id` (`plugin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ticketanalysiscache`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ticketanalysiscache` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `board_id` int(11) unsigned DEFAULT NULL,
  `issue_key` varchar(191) DEFAULT NULL,
  `content_hash` varchar(191) DEFAULT NULL,
  `clarity_score` int(11) unsigned DEFAULT NULL,
  `clarity_analysis` text DEFAULT NULL,
  `reporter_name` varchar(191) DEFAULT NULL,
  `reporter_email` varchar(191) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_foreignkey_ticketanalysiscache_board` (`board_id`)
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

